import { ChangeDetectionStrategy, Component, signal } from '@angular/core';

@Component({
  selector: 'shared-portfolio',
  imports: [],
  templateUrl: './portfolio.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PortfolioComponent {
  portfolio = signal([
    {
      src: 'portfolio/1.png',
      job: 'Developer',
      artist: 'Artist 1',
      album: 'Album 1',
      song: 'Song 1',
    },
    {
      src: 'portfolio/2.png',
      job: 'Designer',
      artist: 'Artist 2',
      album: 'Album 2',
      song: 'Song 2',
    },
    {
      src: 'portfolio/3.png',
      job: 'Engineer',
      artist: 'Artist 3',
      album: 'Album 3',
      song: 'Song 3',
    },
    {
      src: 'portfolio/4.png',
      job: 'Manager',
      artist: 'Artist 4',
      album: 'Album 4',
      song: 'Song 4',
    },
    {
      src: 'portfolio/5.png',
      job: 'Analyst',
      artist: 'Artist 5',
      album: 'Album 5',
      song: 'Song 5',
    },
    {
      src: 'portfolio/6.png',
      job: 'Tester',
      artist: 'Artist 6',
      album: 'Album 6',
      song: 'Song 6',
    },
    {
      src: 'portfolio/7.png',
      job: 'Scrum Master',
      artist: 'Artist 7',
      album: 'Album 7',
      song: 'Song 7',
    },
    {
      src: 'portfolio/8.png',
      job: 'Architect',
      artist: 'Artist 8',
      album: 'Album 8',
      song: 'Song 8',
    },
    {
      src: 'portfolio/9.png',
      job: 'Intern',
      artist: 'Artist 9',
      album: 'Album 9',
      song: 'Song 9',
    },
    {
      src: 'portfolio/10.png',
      job: 'Lead',
      artist: 'Artist 10',
      album: 'Album 10',
      song: 'Song 10',
    },
    {
      src: 'portfolio/11.png',
      job: 'Consultant',
      artist: 'Artist 11',
      album: 'Album 11',
      song: 'Song 11',
    },
    {
      src: 'portfolio/12.png',
      job: 'Coach',
      artist: 'Artist 12',
      album: 'Album 12',
      song: 'Song 12',
    },
    {
      src: 'portfolio/13.png',
      job: 'Support',
      artist: 'Artist 13',
      album: 'Album 13',
      song: 'Song 13',
    },
    {
      src: 'portfolio/14.png',
      job: 'DevOps',
      artist: 'Artist 14',
      album: 'Album 14',
      song: 'Song 14',
    },
    {
      src: 'portfolio/15.png',
      job: 'SysAdmin',
      artist: 'Artist 15',
      album: 'Album 15',
      song: 'Song 15',
    },
    {
      src: 'portfolio/16.png',
      job: 'Database Admin',
      artist: 'Artist 16',
      album: 'Album 16',
      song: 'Song 16',
    },
    {
      src: 'portfolio/17.png',
      job: 'Data Scientist',
      artist: 'Artist 17',
      album: 'Album 17',
      song: 'Song 17',
    },
    {
      src: 'portfolio/18.png',
      job: 'Security Engineer',
      artist: 'Artist 18',
      album: 'Album 18',
      song: 'Song 18',
    },
    {
      src: 'portfolio/19.png',
      job: 'AI Specialist',
      artist: 'Artist 19',
      album: 'Album 19',
      song: 'Song 19',
    },
    {
      src: 'portfolio/20.png',
      job: 'QA Engineer',
      artist: 'Artist 20',
      album: 'Album 20',
      song: 'Song 20',
    },
    {
      src: 'portfolio/21.png',
      job: 'Mobile Dev',
      artist: 'Artist 21',
      album: 'Album 21',
      song: 'Song 21',
    },
    {
      src: 'portfolio/22.png',
      job: 'Frontend Dev',
      artist: 'Artist 22',
      album: 'Album 22',
      song: 'Song 22',
    },
    {
      src: 'portfolio/23.png',
      job: 'Backend Dev',
      artist: 'Artist 23',
      album: 'Album 23',
      song: 'Song 23',
    },
    {
      src: 'portfolio/24.png',
      job: 'Fullstack Dev',
      artist: 'Artist 24',
      album: 'Album 24',
      song: 'Song 24',
    },
    {
      src: 'portfolio/25.png',
      job: 'UX Designer',
      artist: 'Artist 25',
      album: 'Album 25',
      song: 'Song 25',
    },
    {
      src: 'portfolio/26.png',
      job: 'UI Designer',
      artist: 'Artist 26',
      album: 'Album 26',
      song: 'Song 26',
    },
    {
      src: 'portfolio/27.png',
      job: 'Project Manager',
      artist: 'Artist 27',
      album: 'Album 27',
      song: 'Song 27',
    },
    {
      src: 'portfolio/28.png',
      job: 'Product Owner',
      artist: 'Artist 28',
      album: 'Album 28',
      song: 'Song 28',
    },
    {
      src: 'portfolio/29.png',
      job: 'Tech Lead',
      artist: 'Artist 29',
      album: 'Album 29',
      song: 'Song 29',
    },
    {
      src: 'portfolio/30.png',
      job: 'CTO',
      artist: 'Artist 30',
      album: 'Album 30',
      song: 'Song 30',
    },
    {
      src: 'portfolio/31.png',
      job: 'CIO',
      artist: 'Artist 31',
      album: 'Album 31',
      song: 'Song 31',
    },
    {
      src: 'portfolio/32.png',
      job: 'CEO',
      artist: 'Artist 32',
      album: 'Album 32',
      song: 'Song 32',
    },
    {
      src: 'portfolio/33.png',
      job: 'Researcher',
      artist: 'Artist 33',
      album: 'Album 33',
      song: 'Song 33',
    },
    {
      src: 'portfolio/34.png',
      job: 'Game Dev',
      artist: 'Artist 34',
      album: 'Album 34',
      song: 'Song 34',
    },
    {
      src: 'portfolio/35.png',
      job: 'Animator',
      artist: 'Artist 35',
      album: 'Album 35',
      song: 'Song 35',
    },
    {
      src: 'portfolio/36.png',
      job: 'Video Editor',
      artist: 'Artist 36',
      album: 'Album 36',
      song: 'Song 36',
    },
    {
      src: 'portfolio/37.png',
      job: 'Sound Engineer',
      artist: 'Artist 37',
      album: 'Album 37',
      song: 'Song 37',
    },
    {
      src: 'portfolio/38.png',
      job: 'Music Producer',
      artist: 'Artist 38',
      album: 'Album 38',
      song: 'Song 38',
    },
    {
      src: 'portfolio/39.png',
      job: 'Writer',
      artist: 'Artist 39',
      album: 'Album 39',
      song: 'Song 39',
    },
    {
      src: 'portfolio/40.png',
      job: 'Editor',
      artist: 'Artist 40',
      album: 'Album 40',
      song: 'Song 40',
    },
    {
      src: 'portfolio/41.png',
      job: 'grapher',
      artist: 'Artist 41',
      album: 'Album 41',
      song: 'Song 41',
    },
    {
      src: 'portfolio/42.png',
      job: 'Illustrator',
      artist: 'Artist 42',
      album: 'Album 42',
      song: 'Song 42',
    },
    {
      src: 'portfolio/43.png',
      job: 'Marketer',
      artist: 'Artist 43',
      album: 'Album 43',
      song: 'Song 43',
    },
    {
      src: 'portfolio/44.png',
      job: 'Sales',
      artist: 'Artist 44',
      album: 'Album 44',
      song: 'Song 44',
    },
    {
      src: 'portfolio/45.png',
      job: 'HR',
      artist: 'Artist 45',
      album: 'Album 45',
      song: 'Song 45',
    },
  ]);

  selectedIndex: number | null = null;

  onItemClick(index: number) {
    if (this.selectedIndex === index) {
      this.selectedIndex = null; // Deseleccionar si se hace click nuevamente
    } else {
      this.selectedIndex = index;
    }
  }
}
